### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by mileo** [odoo-brazil/odoo-brazil-banking#41]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

# Modules to migrate

- [ ] l10n_br_account_banking_payment
- [ ] l10n_br_account_banking_payment_bradesco_tributos
- [ ] l10n_br_account_banking_payment_cnab
- [ ] l10n_br_account_payment_boleto
- [ ] l10n_br_account_payment_mode
- [ ] l10n_br_cnab400_import
- [ ] l10n_br_cnab_import
